version: "3.9"
services:
  convertium:
    container_name: convertium
    build: .
    ports:
      - "6787:80"
    volumes:
      - './data:/data'
      - '/home/josiah/Downloads/Season 01:/movies'
      # - '/media/storage/public/PlexMedia/tv:/tv'
    environment:
      - TIMEZONE="Pacific/Auckland"
      # - WEBHOOK_ERROR_URL="https://example.com/"
      # - PUID=1000
      # - PGID=1000
    restart: unless-stopped

  # postrges:
  #   image: postgres
  #   volumes:
  #     - './data:/var/lib/postgresql/data'
  #   environment:
  #     - POSTGRES_USER=convertium
  #     - POSTGRES_PASSWORD=convertium
  #     - POSTGRES_DB=convertium
