version: "3.9"
services:
  convertium:
    restart: unless-stopped
    image: ghcr.io/josiahbull/convertium:main
    # build: .
    volumes:
      - '/media/movies:/movies'
      - '/media/tv:/tv'
    environment:
      - TIMEZONE=Pacific/Auckland
      # DEBUG, INFO, WARN, ERROR, CRITICAL
      - LOG_LEVEL=INFO
      # number of minutes between scans
      - SCAN_INTERVAL=20
      # comma separated list of paths to scan
      - BASE_PATHS=/movies,/tv
      # comma separated list of extensions to attempt conversions on
      - VALID_EXTENSIONS=.mp4,.mkv,.avi,.mov,.wmv,.mpg,.mpeg
      # comma seperated list of ffmpeg arguments to pass when converting
      - FFMPEG_ARGUMENTS=-c:v,libx264,-crf,20,-preset,slow,-c:a,mp3,-b:a,192k,-vf,scale=1920:1080,-movflags,+faststart,-loglevel,error,-y
    depends_on:
      - postgres

  postgres:
    restart: unless-stopped
    image: postgres
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=convertium
      - POSTGRES_PASSWORD=convertium
      - POSTGRES_DB=convertium

  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - convertium
      - postgres
