# The log level that you want to be printed/saved as a file,
# valid values are: DEBUG, INFO, WARNING, ERROR, CRITICAL
# the default is INFO.
log_level='INFO'
log_file='./log/convertium.log'
# How often the program should check for new files to convert, in minutes
check_interval_minutes=20
# The path to the directory where the files to convert are located.
base_paths=['/movies', '/tv']
# Valid file extensions to attempt conversion of
valid_extensions=['.mp4', '.mkv', '.avi', '.mov', '.wmv', '.mpg', '.mpeg']
# Arguments to pass to ffmpeg, note that %INPUT_FILE% and %OUTPUT_FILE% are static, and should remain
# as they are, though their position may be altered.
ffmpeg_arguments = ['ffmpeg', '-i', '%INPUT_FILE%', '-c:v', 'libx264', '-preset', 'slow', '-crf', '20', '-c:a', 'mp3', '-b:a', '160k', '-vf', 'format=yuv420p', '-vf', 'scale=1920:1080', '-movflags', '+faststart', '-loglevel', 'error', '-y', '%OUTPUT_NAME%']