name: Test

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    name: Test and Coverage

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: convertium
          POSTGRES_PASSWORD: convertium
          POSTGRES_DB: convertium_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install requirements for Tests
        run: pip install -r dev-requirements.txt

      - name: Run Tests
        run: python -m unittest
        env:
          POSTGRES_HOST: postgres

      - name: Install requirements for coverage
        run: pip install coverage

      - name: Generate Coverage Report
        run: coverage run --branch --context=ci --source src -m unittest && coverage report && coverage lcov -o lcov.info
        env:
          POSTGRES_HOST: postgres

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
          verbose: true
